version: '2'
services:
    api:
        build: api
        ports:
        - "8081:8081"
    web:
        build: web
        ports:
        - "8082:8082"
        links: 
        - mongo
    mongo:
        image: "mongo"