version: '2'
services:
    api:
        build: api
        ports:
        - "9009:9009"
    web:
        build: web
        ports:
        - "9010:9010"
        links: 
        - mongo
    mongo:
        image: "mongo"