version: '2'
services:
    api:
        # Uses Dockerfile in 'api'
        build: api
        ports:
        # Fowards host port to 'api'
        - "9009:9009"
        links: 
        # Links 'mongo' container to 'api'
        - mongo
    web:
        # Uses Dockerfile in 'web'
        build: web
        ports:
        # Fowards host port to 'web'
        - "9010:9010"
    admin:
        # Uses Dockerfile in 'admin'
        build: admin
        ports:
        # Fowards host port to 'admin'
        - "9011:9011"
    mongo:
        # Uses mongo image from Docker hub
        image: "mongo"